# Generated by Django 5.1.2 on 2024-12-22 22:48

import SEapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEapp', '0003_alter_customer_name_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[SEapp.models.validate_price]),
        ),
    ]
